INSERT INTO APP_USER (USER_ID,ACTIVE,DATE_JOINED,FIRST_NAME,SURNAME,USER_NAME,VERSION) VALUES (1,1,{d '2014-01-01'},'admin','admin','admin',0);
INSERT INTO APP_USER (USER_ID,ACTIVE,DATE_JOINED,FIRST_NAME,SURNAME,USER_NAME,VERSION) VALUES (2,1,{d '2014-02-01'},'Jane','Doe','jdoe',0);
INSERT INTO APP_USER (USER_ID,ACTIVE,DATE_JOINED,FIRST_NAME,SURNAME,USER_NAME,VERSION) VALUES (3,1,{d '2014-03-01'},'user','user','user',0);
INSERT INTO APP_USER (USER_ID,ACTIVE,DATE_JOINED,FIRST_NAME,SURNAME,USER_NAME,VERSION) VALUES (4,1,{d '2014-04-01'},'admin2','admin2','admin2',0);


INSERT INTO APP_ROLE (ROLE_ID,ROLE_DESCRIPTION,ROLE_NAME,VERSION) VALUES (1,'Administrator','ROLE_ADMIN',0);
INSERT INTO APP_ROLE (ROLE_ID,ROLE_DESCRIPTION,ROLE_NAME,VERSION) VALUES (2,'Standard User','ROLE_USER',0);

INSERT INTO APP_USERROLE (ROLE_ID,USER_ID) VALUES (1,1);
INSERT INTO APP_USERROLE (ROLE_ID,USER_ID) VALUES (2,1);
INSERT INTO APP_USERROLE (ROLE_ID,USER_ID) VALUES (2,2);
INSERT INTO APP_USERROLE (ROLE_ID,USER_ID) VALUES (2,3);
INSERT INTO APP_USERROLE (ROLE_ID,USER_ID) VALUES (1,4);
INSERT INTO APP_USERROLE (ROLE_ID,USER_ID) VALUES (2,4);
